services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    hostname: nginx
    restart: always
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./key.pem:/certs/key.pem:ro"
      - "./ca.pem:/certs/ca.pem:ro"

    ports:
      - "0.0.0.0:443:443"
      - "0.0.0.0:80:80"
      - ":::443:443"
      - ":::80:80"
    environment:
      NGINX_WORKER_PROCESSES: "4"
      NGINX_WORKER_CONNECTIONS: "768"
    networks:
      - overleaf-network

    healthcheck:
      test: ["CMD-SHELL", "curl -fsI --connect-timeout 10 http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  overleaf-network:
    external: true


